# Generated by Django 3.2.19 on 2023-05-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_buyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
