# Generated by Django 4.1.7 on 2023-04-19 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='День рождение')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='users/profile/', verbose_name='Фото профиля')),
                ('country', models.TextField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('city', models.TextField(blank=True, max_length=168, null=True, verbose_name='Город')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Баланс')),
                ('username', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
