# Generated by Django 4.1.7 on 2023-03-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50, verbose_name='Имя')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='users/profile/', verbose_name='Фото профиля')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Баланс')),
            ],
        ),
    ]
